#pragma once

enum MODEL_ID
{
	TEST_MODEL,
	EARTH_MODEL,

	PLAYER_MODEL,
	PLAYER_BOOSTER_MODEL,
	ENEMY_1_MODEL,
	ENEMY_2_MODEL,
	ENEMY_3_MODEL,
	ENEMY_3_PROPELLER_MODEL,
	STAGE_MODEL,
	SKY_MODEL,
	MOUNTAIN_MODEL,
	MACHINEGUN_MODEL,
	MISSILE_MODEL,

	ENEMY_MACHINEGUN_MODEL,
	ENEMY_MISSILE_MODEL,
	BOSS_AIR_SHIP,
	BOSS_AIR_SHIP_MISSILE_SHOOTER,
	BOSS_AIR_SHIP_MACHINEGUN_SHOOTER,
	BARRIER,
	BARRIER_SPHERE,
	BARRIER_POLE,
	BARRIER_GENERATOR,
	RED_FIGHTER_MODEL,
	CONTAINER_MODEL,
};

enum TEXTURE_ID
{
	TITLE_TEXTURE,
	OSU_TEXTURE,
	TEXT_TEXTURE,
	PT_TEXTURE,
	MINI_KENDOU_TEXTURE,
	MINI_KARATE_TEXTURE,
	RESULT_1_TEXTURE,
	RESULT_2_TEXTURE,


	BLACK_SMOKE_TEX,
	FIRE_TEX,
	SMOKE_TEX,
	LOGO_TEX,
	HP_GAUGE_TEX,
	HP_GAUGE_FRAME_TEX,
	STAR_TEX,
	PLATE_BRONZ_TEX,
	PLATE_SILVER_TEX,
	PLATE_GOLD_TEX,
	CLASS_TEXT_TEX,
	RESULT_NUM_TEX,
	RESULT_SENKA_TEX,
	RESULT_GEKIHA_TEX,
	TITLE_LOGO_TEX,
	RADAR_TEXTURE,
	REFLECT_TEXTURE,
	DASH_LINE_TEXTURE,
	LOCKON_CURSOR_TEX,
	BOSS_GAUGE_FRAME_TEX,
	BOSS_GAUGE_TEX,
	BLACK_BAR_TEX,
	MISSILE_GAUGE_FRAME_TEX,
	MISSILE_GAUGE_TEX,
	MISSILE_GAUGE_BLACK_TEX,
	BLACK_TEX,
	MISS_TEX,
	TUTORIAL_TEX,
};

enum SOUND_ID
{
	TITLE_BGM,
	GAME_BGM,
	RESULT_BGM,

	ATTACK_SE,
	HIT_SE,
	
	START_SE,
	TIME_OVER_SE,

	BOMB_SMOLL_SE,
	BOMB_MIDDLE_SE,
	BOMB_BIG_SE,
	DAMAGE_SE,
	RECEPTION_SE,
	REFRECT_SE,
	MISSILE_SE,
};